### ISSUE TITLE
angrgdb remote debugging

### ISSUE THREAD

**Issue by mahmoudaghvami** [andreafioraldi/angrgdb#2]
Dear Andrea Fioraldi,
I'm trying to extend angrgdb for Android app debugging. We are debugging an Android app using a typical gdbserver on Android emulator. (In contrast with AngrIDA we have no IDA server or anything)
In angrgdb you have "stateShot" which returns an angr state from the current debugging session. What will happen when we want to do that in a remote debugging mode?
As I understand, If I want to connect angr to a debugger, I should implement abstracts from angrdbg.
What should I do with "beforeStateShot" in remote debugging mode?
I'm new in this field, but I will be happy if I can contribute angrgdb even a little.
Thanks in advance for  your help and consideration

**Comment by andreafioraldi** [comment]
The remote feature is not related to remote debugging but to a remote python process running angr on a supercomputer.
angrdbg is debugger agnostic so if you want to use angrgdb with a gdbserver you can do it without changing anything.
Simply run gdb in a machine with angrgdb installed, connect to the remote gdbserver and use angrgdb.
You shouldn't expect a tool without bugs or limitations, angrgdb is a experimental use case for my Bsc thesis at the moment.

**Comment by andreafioraldi** [comment]
i never tested angrgdb with a remote gdbserver but it should work, please report me any issues

**Comment by mahmoudaghvami** [comment]
You are right. Angrgdb worked with the remote gdbserver. 
Thanks for your interesting tool

**Comment by maxwell-bland** [comment]
Currently using this tool in some research! Amazing work. I found an issue when using this to analyze a ARM Cortex A8 processor which was being emulated through QEmu. Since the vmmap and file were not being exported by the gdbserver, this caused angrgdb to fail out.

pwndbg implements a hacky version of the vmmap command which infers the QEmu virtual memory map. Since gdb reports a pid of 42000 as a magic number in cases where it cannot find the real PID, I fixed up the execution by adding the following snippet to get_vmmap. (I also needed to fix some type checking in Angr, but that is a separate issue.)

Excuse the gross parsing code below; I was looking for a quick workaround. 

I'll share this here for people that happen to stumble on this issue as well, and for future reference.

```python
        if pid != 42000:
            mpath = "/proc/%s/maps" % pid
            out = open(mpath).read()
            pattern = re.compile(
                "([0-9a-f]*)-([0-9a-f]*) ([rwxps-]*)(?: [^ ]*){3} *(.*)")
            # 00400000-0040b000 r-xp 00000000 08:02 538840  /path/to/file
            matches = pattern.findall(out)
        else:
            out = gdb.execute('vmmap', to_string=True).split('\n')[2:-1]
            matches = []
            for i,match in enumerate(out):
                match = match.strip()
                match = ''.join(list(filter(lambda x: x in string.printable, match)))
                match = match.split()
                if '0x' not in match[0]:
                    match = match[1:]
                else:
                    match[0] = '0x' + match[0].split('0x')[1]
                print(match)
                matches.append((match[0][2:],match[1][2:],match[2], '.map%d' % (i)))
```

**Comment by disconnect3d** [comment]
Hey, @maxwell-bland that's pretty smart ;). Would you mind sending a PR to pwndbg that would give the user an option to fetch maps via parasing QEMU process maps file?

**Comment by andreafioraldi** [comment]
@maxwell-bland I usually add monitor commands to get the pid when interacting with unusual targets like the gdbserver of Intel PIN and then simply `get_debugger().pid = my_pid` before StateShot.
Regards pwndbg, it replaces builtins.int and it is not compatible with angrgdb.
angr is full of `type(var) == int` and this is an angr issue not mine.
